---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.7
  - name: centos-7.2
    driver:
      box_version: '2.2.9'
  - name: ubuntu-14.04

suites:
  - name: default-404
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '4.0.4'

  - name: default-407
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '4.0.7'
        java:
          jdk_version: '8'
    excludes:
      - ubuntu-14.04
      - centos-6.7

  - name: default-305
    run_list:
      - recipe[karaf_test::install]
    attributes:
      karaf_test:
        version: '3.0.5'

  - name: remove
    run_list: 
      - recipe[karaf_test::remove]

  - name: install-remove
    run_list: 
      - recipe[karaf_test::install]
      - recipe[karaf_test::remove]

#  - name: slow-cloud
#    run_list:
#      - recipe[karaf_test::install]
#    attributes:
#      karaf_test:
#        version: '3.0.3'
#    driver:
#      customize:
#        cpuexecutioncap: 25
#    excludes:
#      - ubuntu-14.04
