AllCops:
  Include:
    - 'Berksfile'
    - 'Gemfile'
    - 'Rakefile'
    - 'Thorfile'
    - 'Guardfile'
  Exclude:
    - '**/metadata.rb'

ExtraSpacing:
  Enabled: false
HashSyntax: 
  Enabled: false
LineLength:
  Max: 120
SpaceBeforeFirstArg:
  Enabled: false
TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
TrailingWhitespace:
  Enabled: false
WordArray: 
  Enabled: false
